spring:
  application:
    name: server

server:
  port: 8080

logging:
  level:
    org.springframework: ERROR
    kz.turebekov: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: server/src/log-files/app.log
